x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-debug}

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      <<: *shared_environment
      AI_BINARY_PATH: /app/game-ai
    ports:
      - '8080:8080'

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
